@echo off

echo Running preprocess_data.py...
python scripts\preprocess_data.py
echo preprocess_data.py finished. Press Enter to continue...
pause > nul

echo Running clean_sentiment.db.py...
python scripts\clean_sentiment.db.py
echo clean_sentiment.db.py finished. Press Enter to continue...
pause > nul

echo Running calculate_sentiment.py...
python scripts\calculate_sentiment.py
echo calculate_sentiment.py finished. Press Enter to continue...
pause > nul

echo All scripts executed successfully.
pause
